// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwALVNa36equB2U6Nume2SOasxtaneSyY',
    appId: '1:986810199730:web:b7f0e61ba1258fad4be3ab',
    messagingSenderId: '986810199730',
    projectId: 'todow-f37ac',
    authDomain: 'todow-f37ac.firebaseapp.com',
    storageBucket: 'todow-f37ac.firebasestorage.app',
    measurementId: 'G-YKELZPYQDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJH4no-ifGZdfCz9R227awHQ95XX3HLpA',
    appId: '1:986810199730:android:ea7bd20faa7a71ce4be3ab',
    messagingSenderId: '986810199730',
    projectId: 'todow-f37ac',
    storageBucket: 'todow-f37ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnbgegE_ZIXQ8nuo8VYsAWMaT8bFhStKA',
    appId: '1:986810199730:ios:30813a8bd37525f84be3ab',
    messagingSenderId: '986810199730',
    projectId: 'todow-f37ac',
    storageBucket: 'todow-f37ac.firebasestorage.app',
    iosBundleId: 'com.example.todowTodoManager',
  );
}
